name: Circle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
            cd circle
            go mod download

      - name: Run tests
        run: |
            cd circle
            go test -v ./...
  build-and-push:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的虚拟机

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 从 GitHub 仓库检出代码到虚拟机

      - name: Test Docker Hub connectivity
        run: |
          curl -I https://hub.docker.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # 设置 Docker Buildx 以支持多平台构建

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub 用户名，从仓库 Secrets 中获取
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Docker Hub 密码，从仓库 Secrets 中获取

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # 构建上下文，即 Dockerfile 所在的目录
          push: true  # 推送镜像到 Docker 镜像仓库
          tags: |
            luohuixi/circle-backend:latest  
            luohuixi/circle-backend:${{ github.sha }}  